version: "3"
services:
  mariadb:
    image: mariadb:11.3.2
    ports:
      - "13306:3306"
    environment:
      - TZ="Asia/Seoul"
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=batch_example_db
    restart: on-failure
